title = "Python程序基本结构 - 复杂的数学运算"
cases = [
    ["{\"x\": 2, \"y\": 3, \"z\": 4, \"n\": 2}", "10.0"],
    ["{\"x\": 1, \"y\": 2, \"z\": 3, \"n\": 3}", "14.0"],
    ["{\"x\": 5, \"y\": 6, \"z\": 7, \"n\": 4}", "330.0"],
]
timeout = 4
descriptions = """
## 简述
使用Python编程语言来完成一些复杂的数学运算。这个任务需要你理解和应用多种数学公式和Python编程知识。

## 任务目标  
你的任务是编写一个Python程序，该程序将接收一个JSON字符串作为输入，该字符串包含四个键值对，分别是`x`, `y`, `z`和`n`。你需要使用这四个值来计算以下公式的结果：

`Result = x^n + y^n + z^n + n!`

其中，`n!`表示n的阶乘。你可以使用math模块来计算阶乘和幂运算。

请注意，你需要处理的是浮点数，所以在比较和输出结果时，应保留一位小数。

 - 输入一个JSON字符串，例如：`{\"x\": 2, \"y\": 3, \"z\": 4, \"n\": 2}`。
 - 输出计算结果，保留一位小数（例如：`10.0`）。"""
