title = "初入Python - Hello, world！"
stdin = ""
stdout = "Hello, world!"
timeout = 4
descriptions = """
# 欢迎来到Python的世界！
Python是一门优雅而健壮的编程语言，它继承了传统编译语言的强大性和通用性，同时也借鉴了简单脚本和解释语言的易用性。它可以帮你完成工作，而且一段时间以后，你还能看明白自己写的这段代码。  
不得不说，Python真的是很优秀的一门编程语言。曾经我也以为Python是所谓的“功能不全”“代码简陋”的“胶水”语言，但现在看来你也没有担心的必要……别看了，这个系统就是用Python写的！

## 你知道`Hello World`是什么吗？
《`The C Programming Language`》（一本C语言教程）中，使用了`Hello, World`作为了第一个示例代码，很快被许多人知道。随后，大家都开始用`Hello, World`作为自己初入一门新编程语言的第一次编码。  
怎么，你也要来写代码了？  
点击下方按钮开始书写代码！希望这个学期玩得愉快！  
###### <span title=\"请务必在信息课上喊出来，许老师会给你当头一棒\">如果你已经通关了，请务必夸一夸自己！</span>

## 本关要求
 - 输出一次`Hello, world!`（建议拷贝过去，因为要求一字不差）
 - 用`print()`方法输出！

#### 注：今后没有注明的情况下，代码限时4秒！
##### 更不要想破解这个系统"""
