title = "初识Python - For循环"
iscases = true
cases = [
    [
        "10057939",
        "1",
    ],
    [
        "10000011",
        "0",
    ],
]
timeout = 8
descriptions = """
# 初识Python - For 循环
Python for 循环可以遍历任何可迭代对象，如一个列表或者一个字符串。

## for 循环语句（先看上一行字）
「说人话！」  
首先，for循环的一般格式如下：  
```python
for <variable> in <sequence>:
    <statements>
else:  # if there isn't anything in sequence
    <statements>
```

## `for ... in range()` 语句
`range(n)`是一个神奇的函数。当你输入`1`时，它会给你`0`；当你输入`3`时，它会返回`[0, 1, 2]`。  
即：输入`n`，返回`0`到`n`（不含`n`）的所有数。
`range(a, n)`也类似，不过是返回a（默认为`0`）到n（不含`n`）的所有数。
`range(a, n, step)`也类似，不过是返回`a`到`n`（不含`n`）的所有数，且步长为`step`（默认为`1`）。

利用这个函数，我们可以快速实现一段计次循环（如指定循环`n`次）。  
```python
for i in range(10):
    <statements>  # 此处的代码将会被执行10次
```

#### 如果你学过c/c++，也可以看看：
上述代码等同于：
```cpp
#include <_mingw.h>
// 只包含基本语法的头文件
using namespace std;
int main(int argc, const char* argv) {
    for (int i = 0; i < 10; i ++) {
        <statements>;  // 此处的代码将会被执行10次
    }
}
```

###### 是不是非常的简单呢？

## 任务目标
小明同学准备了一个数，认为这个数是个质数。但是旁边的小日月同学认为，这个数一定是个合数。请你帮<span title=\"想不到吧，我故意的🙂\">小明和小明同学</span>看看，这个数是不是质数？  

 - 任务有一定难度。
 - 不需要使用<span title=\"你要不要看看多线程模块存不存在？\">多线程</span>加速。
 - 首先输入一个数，然后判断这个数是否为质数。如果这个数为质数则输出1，否则输出0"""
