title = "Python程序基本结构 - 圆的面积"
iscases = true
# cases: [[input, output], ...]
cases = [
    [
        "2",
        "12.56",
    ],
    [
        "1",
        "6.28",
    ],
    [
        "3",
        "18.84",
    ],
]
timeout = 4
descriptions = """
## 简述
本题过于简单，请直接根据任务目标完成任务。

## 任务目标  
小红同学手中有一个圆规，并把圆的半径测量了出来，请计算圆的周长。（`pi=3.14`, `C=你猜？`）

 - 输入半径（想想你要做<span title=\"输入的是____，而计算需要____\">什么</span>！！）
 - 输出周长"""
