title = "Python基本算法 - 三角形的面积"
cases = [["3,4,5", "6.0"], ["5,12,13", "30.0"], ["7,24,25", "84.0"]]
timeout = 4
descriptions = """
## 简述
在这个挑战中，你将使用Python编程语言来计算三角形的面积。这是一个基本的编程任务，但它需要你理解和应用数学公式。

## 任务目标  
小明同学正在学习三角形的面积计算，他知道了三角形的三边长度，但是不知道如何计算面积。你的任务是编写一个Python程序，该程序将接收三角形的三边长度作为输入，并输出其面积。

你需要使用海伦公式来计算面积，海伦公式是一个非常实用的公式，可以用三角形的三边长度来计算其面积。公式如下： `Area = sqrt[s(s-a)(s-b)(s-c)]`，其中`s=(a+b+c)/2`。

请注意，你需要处理的是浮点数，所以在比较和输出结果时，应保留一位小数。

 - 输入三角形的三边长度，以逗号分隔（例如：“3,4,5”）。
 - 输出三角形的面积，保留一位小数（例如：“6.0”）。


### 温馨提示
 - 沙盒中环境受到限制，部分模块不可用

"""
